# https://docs.travis-ci.com/user/languages/perl/
---
dist: focal

language: perl

perl:
  - "5.30.0"
  - "5.26.0"

notifications:
  recipients:
    - michael@thedarkwinter.com
  email:
    on_success: change
    on_failure: always
