# https://docs.travis-ci.com/user/languages/perl/
---

language: perl

jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: bionic

notifications:
  recipients:
    - michael@thedarkwinter.com
  email:
    on_success: change
    on_failure: always
